on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'EricsGoods_v*' # Push events to matching EricsGoods_vv*, i.e. EricsGoods_v1.0, EricsGoods_v20.15.10

  watch:
    types: [started]

name: Upload Release Asset

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    if: github.actor == github.event.repository.owner.login
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project # This would actually build your project, using zip for an example artifact
        run: |
          if [ $GITHUB_REF == *master ]; then ZIPNAME = 'EricsGoods' else ZIPNAME = $GITHUB_REF fi
          echo $ZIPNAME
          mkdir ./Mods
          mv ./EricsGoods/Modlet\ readme.md .
          mv ./EricsGoods/release.md .
          mv ./EricsGoods ./Mods
          zip -r $ZIPNAME Mods Modlet\ readme.md release.md
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1.6.1
        with:
          name: ${{ github.ref }}
          bodyFile: release.md
          artifact: ${{ github.ref }}.zip
          artifactContentType: application/zip
          draft: true
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
